# This workflow will do a clean install of the dependencies and run tests across different versions
#
# Replace <track> with the track name
# Replace <image-name> with an image to run the jobs on
# Replace <action to setup tooling> with a github action to setup tooling on the image
# Replace <install dependencies> with a cli command to install the dependencies
#
# Find Github Actions to setup tooling here:
# - https://github.com/actions/?q=setup&type=&language=
# - https://github.com/actions/starter-workflows/tree/main/ci
# - https://github.com/marketplace?type=actions&query=setup
#
# Requires scripts:
# - bin/test

name: J / Test

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633

      - name: Install project dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends wget ca-certificates

      - name: Install J
        run: |
          wget https://www.jsoftware.com/download/j9.5/install/j9.5_linux64.tar.gz
          tar -xvf j9.5_linux64.tar.gz
          mv j9.5 /opt/j9.5
          rm -rf j9.5_linux64.tar.gz

      - name: Verify all exercises
        run: bin/verify-exercises.sh
